[workspace]
members = ["crates/tessera-core", "crates/tessera-windows", "crates/tessera"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/redstone-md/tessera"
license = "GPL-3.0-only"
readme = "README.md"

[workspace.dependencies]
tessera-core = { path = "crates/tessera-core" }
tessera-windows = { path = "crates/tessera-windows" }
windows-sys = "0.61.2"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
