[workspace]
members = ["crates/tessera-core", "crates/tessera"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/redstone-md/tessera"

[workspace.dependencies]
tessera-core = { path = "crates/tessera-core" }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
