[package]
name = "tessera-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
description = "Native alpha desktop presentation for Tessera"
publish = false

[dependencies]
slint.workspace = true
parking_lot.workspace = true

[target.'cfg(windows)'.dependencies]
slint = { workspace = true, features = ["unstable-winit-030"] }

[build-dependencies]
slint-build.workspace = true

[dev-dependencies]
i-slint-backend-testing.workspace = true
slint = { workspace = true, features = ["unstable-winit-030", "renderer-femtovg"] }

[lints]
workspace = true
